### ISSUE TITLE
2.05 Testing: Perform 2.05 test fork on xenon / testnet

### ISSUE THREAD

**Issue by pavitthrap** [blockstack/stacks-blockchain#2889]
Need to define `BITCOIN_TESTNET_2_0_LAST_BLOCK_HEIGHT` and update `STACKS_EPOCHS_TESTNET` in `src/core/mod.rs`.

**Comment by jcnelson** [comment]
Let's try and get this done by this Thursday at the latest (ideally Wednesday)

**Comment by kantai** [comment]
To recap the action items before a launch on testnet can occur:

- [ ] Review and Merge #2925 -- requires two approvals (pinging @kantai and @gregorycoppola)
- [ ] Review and Merge #2924 -- requires two approvals (pinging @jcnelson and @gregorycoppola)
- [ ] Review and Merge #2923 -- requires one more approval (pinging @jcnelson)
- [ ] Merge #2920 -- approved, should be ready to merge (pinging @jcnelson)
- [ ] Deploy `next-costs` branch to a testnet follower, confirm that it can follow the current testnet, reuse existing chainstate. This can be tested before the above PRs merge.
- [ ] Pick testnet block height, (proposal: 2,104,364 = 48 * 6 + 2104076 ~= 48 hours from now) and open configuration PR (@kantai)
- [ ] Review and Merge configuration PR
- [ ] Tag a next-costs build and deploy to testnet nodes

**Comment by kantai** [comment]
Testnet fork activated! 

https://explorer.stacks.co/txid/0xef13fb69ad25f49400fad61d82fb678cb59f8e584acd70450acd84b3e49ef706?chain=testnet
